import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({ resetPasswordForEmail:vi.fn(),resend:vi.fn(),getUser:vi.fn(),updateUser:vi.fn() }));
vi.mock("@/lib/supabase/server",()=>({ createClient:async()=>({auth:mocks}) }));
import { requestPasswordResetAction, updatePasswordAction, resendConfirmationAction } from "./recovery-actions";
const form=(values:Record<string,string>)=>{const result=new FormData(); for(const [key,value] of Object.entries(values)) result.set(key,value); return result;};
beforeEach(()=>{vi.resetAllMocks();vi.stubEnv("NEXT_PUBLIC_SITE_URL","https://app.example.com");mocks.resetPasswordForEmail.mockResolvedValue({error:null});mocks.resend.mockResolvedValue({error:null});mocks.getUser.mockResolvedValue({data:{user:{id:"verified-user"}},error:null});mocks.updateUser.mockResolvedValue({error:null});});
afterEach(()=>vi.unstubAllEnvs());
describe("account recovery",()=>{
  it("rejects malformed email without sending",async()=>{expect(await requestPasswordResetAction({},form({email:"bad"}))).toHaveProperty("error");expect(mocks.resetPasswordForEmail).not.toHaveBeenCalled();});
  it("normalizes email and uses the fixed PKCE callback",async()=>{expect(await requestPasswordResetAction({},form({email:" OWNER@Example.com "}))).toEqual({success:true});expect(mocks.resetPasswordForEmail).toHaveBeenCalledWith("owner@example.com",{redirectTo:"https://app.example.com/auth/callback?next=/auth/reset-password"});});
  it("does not expose provider details or account existence errors",async()=>{mocks.resetPasswordForEmail.mockResolvedValue({error:{message:"private account information"}});const result=await requestPasswordResetAction({},form({email:"owner@example.com"}));expect(result.success).toBeUndefined();expect(result.error).not.toContain("private");});
  it("refuses an invalid configured redirect origin",async()=>{vi.stubEnv("NEXT_PUBLIC_SITE_URL","javascript:alert(1)");expect(await requestPasswordResetAction({},form({email:"owner@example.com"}))).toHaveProperty("error");expect(mocks.resetPasswordForEmail).not.toHaveBeenCalled();});
  it("requires matching passwords before reaching Auth",async()=>{expect(await updatePasswordAction({},form({password:"new-password-one",password_confirmation:"new-password-two"}))).toHaveProperty("error");expect(mocks.getUser).not.toHaveBeenCalled();});
  it("refuses an unauthenticated direct password update",async()=>{mocks.getUser.mockResolvedValue({data:{user:null},error:null});expect(await updatePasswordAction({},form({password:"new-password-one",password_confirmation:"new-password-one"}))).toHaveProperty("error");expect(mocks.updateUser).not.toHaveBeenCalled();});
  it("refuses a failed server-side user verification",async()=>{mocks.getUser.mockResolvedValue({data:{user:{id:"unverified"}},error:{message:"expired"}});expect(await updatePasswordAction({},form({password:"new-password-one",password_confirmation:"new-password-one"}))).toHaveProperty("error");expect(mocks.updateUser).not.toHaveBeenCalled();});
  it("reports success only after Auth accepts the new password",async()=>{expect(await updatePasswordAction({},form({password:"new-password-one",password_confirmation:"new-password-one"}))).toEqual({success:true});expect(mocks.updateUser).toHaveBeenCalledWith({password:"new-password-one"});});
  it("reports update errors without false success",async()=>{mocks.updateUser.mockResolvedValue({error:{message:"requires reauthentication"}});expect(await updatePasswordAction({},form({password:"new-password-one",password_confirmation:"new-password-one"}))).toHaveProperty("error");});
  it("resends confirmation using the fixed signup destination",async()=>{expect(await resendConfirmationAction({},form({email:"owner@example.com"}))).toEqual({success:true});expect(mocks.resend).toHaveBeenCalledWith({type:"signup",email:"owner@example.com",options:{emailRedirectTo:"https://app.example.com/auth/confirm?next=/onboarding"}});});
});
