// Auto-generated by scripts/generate-build-info.mjs -- do not edit by hand.
// Regenerated on every "npm run dev"/"npm run build" (see package.json).
export const LATEST_MIGRATION: string | null = "20260910140000_restore_reconciliation_claim_guarantees.sql";
export const MIGRATION_COUNT: number = 44;
