// Auto-generated by scripts/generate-build-info.mjs -- do not edit by hand.
// Regenerated on every "npm run dev"/"npm run build" (see package.json).
export const LATEST_MIGRATION: string | null = "20260916100000_feedback_comment_grants.sql";
export const MIGRATION_COUNT: number = 52;
