import { LATEST_MIGRATION, MIGRATION_COUNT, BUILD_VERCEL_ENV } from "@/lib/build-info";

/**
 * Round-4 finding R4-01. Production had no way to prove which commit was
 * actually deployed -- the Vercel Git webhook had silently stopped firing
 * at some point before round 1, and nothing detected it: the Deployments
 * dashboard still showed a "Ready" build (just an old one), and there was
 * no automated check comparing what was *deployed* against what was
 * *pushed*. Reads only Vercel's own System Environment Variables
 * (https://vercel.com/docs/projects/environment-variables/system-environment-variables)
 * and this build's own compile-time migration snapshot (lib/build-info.ts,
 * generated by scripts/generate-build-info.mjs) -- no secrets, no database
 * connection, no credentials of any kind.
 *
 * `VERCEL_GIT_COMMIT_SHA`/`VERCEL_ENV` are only populated at RUNTIME if the
 * Vercel project has "Automatically expose System Environment Variables"
 * enabled (Project Settings -> Environment Variables) -- this is an
 * external Vercel project setting this repository cannot enforce; see
 * DEPLOYMENT.md.
 *
 * Deliberately fails loud (503, `ok: false`) rather than silently
 * reporting success when release metadata is missing in a
 * production/preview environment -- the exact class of gap that let
 * production run un-verified, stale code for as long as it did. Locally
 * (no Vercel involved at all) this is expected and not an error.
 *
 * Round-5 finding R5-05: the check above used to decide "is this a
 * deployed environment" from process.env.VERCEL_ENV -- the exact same
 * runtime variable the disabled-toggle failure mode also suppresses. A
 * misconfigured project (toggle off) then read as plain `environment:
 * "development", ok: true` at runtime: the disabled toggle hid its own
 * evidence. BUILD_VERCEL_ENV (lib/build-info.ts) is captured at BUILD
 * time instead, when Vercel's build step always has VERCEL_ENV available
 * regardless of that runtime-exposure toggle -- so "was this build made
 * by Vercel as production/preview" can no longer be silenced by the same
 * setting that also hides commitSha.
 */
export async function GET() {
  const runtimeEnv = process.env.VERCEL_ENV ?? null;
  const commitSha = process.env.VERCEL_GIT_COMMIT_SHA ?? null;
  const commitRef = process.env.VERCEL_GIT_COMMIT_REF ?? null;

  const isDeployedEnvironment = BUILD_VERCEL_ENV === "production" || BUILD_VERCEL_ENV === "preview";
  const missingReleaseMetadata = isDeployedEnvironment && !commitSha;
  const environment = runtimeEnv ?? BUILD_VERCEL_ENV ?? "development";

  const body = {
    ok: !missingReleaseMetadata,
    environment,
    commitSha,
    commitRef,
    latestMigration: LATEST_MIGRATION,
    migrationCount: MIGRATION_COUNT,
    ...(missingReleaseMetadata
      ? {
          error:
            "This build was made on Vercel as production/preview (BUILD_VERCEL_ENV), but " +
            "VERCEL_GIT_COMMIT_SHA is not visible at runtime -- either this deployment did not go " +
            "through Vercel's Git integration, or the project's 'Automatically expose System " +
            "Environment Variables' setting is disabled. See DEPLOYMENT.md.",
        }
      : {}),
  };

  return Response.json(body, { status: missingReleaseMetadata ? 503 : 200 });
}
