import { LATEST_MIGRATION, MIGRATION_COUNT } from "@/lib/build-info";

/**
 * Round-4 finding R4-01. Production had no way to prove which commit was
 * actually deployed -- the Vercel Git webhook had silently stopped firing
 * at some point before round 1, and nothing detected it: the Deployments
 * dashboard still showed a "Ready" build (just an old one), and there was
 * no automated check comparing what was *deployed* against what was
 * *pushed*. Reads only Vercel's own System Environment Variables
 * (https://vercel.com/docs/projects/environment-variables/system-environment-variables)
 * and this build's own compile-time migration snapshot (lib/build-info.ts,
 * generated by scripts/generate-build-info.mjs) -- no secrets, no database
 * connection, no credentials of any kind.
 *
 * `VERCEL_GIT_COMMIT_SHA`/`VERCEL_ENV` are only populated at runtime if the
 * Vercel project has "Automatically expose System Environment Variables"
 * enabled (Project Settings -> Environment Variables) -- this is an
 * external Vercel project setting this repository cannot enforce; see
 * DEPLOYMENT.md.
 *
 * Deliberately fails loud (503, `ok: false`) rather than silently
 * reporting success when release metadata is missing in a
 * production/preview environment -- the exact class of gap that let
 * production run un-verified, stale code for as long as it did. Locally
 * (no VERCEL_ENV at all) this is expected and not an error.
 */
export async function GET() {
  const environment = process.env.VERCEL_ENV ?? "development";
  const commitSha = process.env.VERCEL_GIT_COMMIT_SHA ?? null;
  const commitRef = process.env.VERCEL_GIT_COMMIT_REF ?? null;

  const isDeployedEnvironment = environment === "production" || environment === "preview";
  const missingReleaseMetadata = isDeployedEnvironment && !commitSha;

  const body = {
    ok: !missingReleaseMetadata,
    environment,
    commitSha,
    commitRef,
    latestMigration: LATEST_MIGRATION,
    migrationCount: MIGRATION_COUNT,
    ...(missingReleaseMetadata
      ? {
          error:
            "VERCEL_GIT_COMMIT_SHA is not set in a production/preview environment -- " +
            "either this deployment did not go through Vercel's Git integration, or " +
            "the project's 'Automatically expose System Environment Variables' setting " +
            "is disabled. See DEPLOYMENT.md.",
        }
      : {}),
  };

  return Response.json(body, { status: missingReleaseMetadata ? 503 : 200 });
}
