// Auto-generated by scripts/generate-build-info.mjs -- do not edit by hand.
// Regenerated on every "npm run dev"/"npm run build" (see package.json).
export const LATEST_MIGRATION: string | null = "20260906090000_fix_confirm_toctou_and_revoke_leaked_token_grant.sql";
export const MIGRATION_COUNT: number = 19;
