// Auto-generated by scripts/generate-build-info.mjs -- do not edit by hand.
// Regenerated on every "npm run dev"/"npm run build" (see package.json).
export const LATEST_MIGRATION: string | null = "20260905193325_server_owned_notification_email_change_budget.sql";
export const MIGRATION_COUNT: number = 18;
export const BUILD_VERCEL_ENV: string | null = null;
